export const SignUpURL = '/auth/register'
export const SignInURL = '/auth/login'
export const ProfileURL = '/auth/profile'
export const VerifyAccountURL = '/auth/verify/account'
export const VerifyPasswordURL = '/auth/verify/password'
export const CreateSchoolURL = '/school'
export const FetchSchoolURL = '/school'
