FROM php:7.4.0-fpm

RUN apt-get update

RUN apt-get install --yes --no-install-recommends imagemagick libmagickcore-dev libmagickwand-dev libpq-dev git unzip curl sendmail libfreetype6-dev libjpeg62-turbo-dev libpng-dev

RUN docker-php-ext-install pdo_pgsql pdo_mysql

RUN docker-php-ext-configure gd --with-freetype --with-jpeg

RUN docker-php-ext-install gd

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer;

RUN apt-get install -y cron htop nano

RUN chmod +x -R /var/www/html

RUN pecl install xdebug

RUN docker-php-ext-enable xdebug

RUN pecl install imagick

RUN docker-php-ext-enable imagick

RUN chmod +x run_test.sh

RUN apt-get install --yes sqlite3
